### ISSUE TITLE
Flash from file does not work

### ISSUE THREAD

**Issue by MattBright01** [balena-io/etcher#4352]
- **Etcher version: 1.19.25** 
- **Operating system and architecture: Windows 10 Intel Celeron 2.13 Ghz 8Gb RAM ** 
- **Image flashed: haos_generic-x86-64-13.2.img** 
- **What do you think should have happened: Open the source** 
- **What happened: Error opening Source   Error: (0 , h.requestMetadata) is not a function  **
- **Do you see any meaningful error information in the DevTools?  No**

**Comment by MattBright01** [comment]
Problem solved with version 1.18
Can be dowloaded for Windows here: https://etcher.fr.uptodown.com/windows/telecharger/106963802

**Comment by lurch** [comment]
> * **What happened: Error opening Source   Error: (0 , h.requestMetadata) is not a function  **

See #4150 

Be careful with downloading Etcher from 3rd-party websites as apparently there are "fake" versions #3724
Official old releases of Etcher can be downloaded from https://github.com/balena-io/etcher/releases

**Comment by imagine496** [comment]
Hi, i have the same problem , and now i see an answer but lurch warns about fake websites, how can i verify that the link he gives is official? or if  Matts link is ok,, heck i havent got very far with trying to get Lynux Mint, this is my second day trying to do what should only take minutes, please advise thank you
![etcher flash from file error](https://github.com/user-attachments/assets/7179c8e6-9462-47f0-b485-dae8154ce812)

**Comment by MattBright01** [comment]
Hi, I had no problem with this link. I simply found it by searching on Google. Otherwise, you can download the version you need here on Github too, as @lurch explains.

**Comment by danilogco** [comment]
Still happening with the latest version. It worked with v1.18.8.

**Comment by jnorre** [comment]
Happening for me too: Official **balenaEtcher-1.19.25-x64.AppImage** from github releases on Ubuntu 24.04.01 LTS.

**Comment by vmario89** [comment]
same problem on TuxedoOS

**Comment by sparevermicelli** [comment]
Same issue, Win10 + 1.19.25

**Comment by ShoGUN1Master** [comment]
Same issue 12.12.2024 Win 11!

**Comment by carlitos816** [comment]
Same issue MACOS Ventura 13.6.9, tried two different Ubuntu ISOs

**Comment by OzHershy** [comment]
I have the same issue and am using the very latest version, I am trying to load Ubuntu onto a working 5 year old HP laptop running Windows 10.

**Comment by ffovert-tech** [comment]
Just open balenaEtcher as an administrator; that worked for me.
