### PR TITLE
Modernize build pipeline

### LINKED ISSUE #2826: Checksums not to be found?
- **1.5.45** 
- **Windows 10** 
- **No images flashed** 

Hello, there are a few references to verifying these releases in different issues, but the current release's checksum is either an HTTP 406 error or Not Found. 

https://github.com/balena-io/etcher/releases/download/v1.5.45/SHASUMS256.txt

Are the checksums still on GitHub? If so, where?

### LINKED ISSUE #2870: Provide packages for ARM architectures
Should provide packages which can be used e.g. on Raspbian to burn image when running on a Raspberry Pi. Currently should be possible to build from source, but packages would make things a lot easier for users.

### LINKED ISSUE #3263: AppImage problem on debian (with a workaround)
- **Etcher version: 1.5.101-x64** 
- **Operating system and architecture: Debian x64** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

I found the Etcher.AppImage to work fine on ubuntu and mint but had issues on debian
just double clicking the image in debian did nothing unlike ubuntu and mint where the app just launched and everything worked fine.

After attempting to launch the image via terminal i found i had to launch it via sudo for root permissions as the app did not ask itself like on the other os's.
then I found it to error on missing ffmpeg
so i installed ffmpeg
Then i could launch from terminal via sudo and it worked.
Then adding the image to pkexec list of allowed apps i managed to get a gui launcher without the terminal window.
With the pkexec method being a complicated procedure for some to do or even knowing you can do it in the first place i thought i'd add a quick how-to to the Etcher forum
https://forums.balena.io/t/howto-etcher-appimage-on-debian/161789/12

One of your team suggested i raised this issue with you so i am doing so.
Personally it's not actually an issue for me as i made a work-around :)
But issue raised as requested :)
Thanks for the good work and great software :)
Bruce

### LINKED ISSUE #3269: Unable to package using electron-Build
- **Etcher version:1.5.102
- **Operating system and architecture:WIN10 

The latest 1.5.102 was constructed normally with ` **make electrone-develop**` under WINODWS10 and operated normally with `npm start`, but packaging could not be completed withe **`electrone-build`**. How can we solve the following errors?

image

### LINKED ISSUE #3292: can not to build on MS-Windows
- **Etcher version:1.15.102+
- **Operating system and architecture:win10

Tiffutil is a macOS program. When packaged on Windows using make electron-build, the error message that tiffutil cannot be found appears!

### LINKED ISSUE #3400: built from source wrong at last when building on arm64 arch system.
- **Etcher version: 1.5.113 (bulit from source) : 2021.01.05 14:00:00
- **Operating system and architecture: debian , arm64
- **Image flashed: not yet
- **Do you see any meaningful error information in the DevTools?** 

the error info were: 
```
• writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=arm64 electron=9.4.0 appOutDir=dist/linux-arm64-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v9.4.0/electron-v9.4.0-linux-arm64.zip size=77 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v9.4.0/electron-v9.4.0-linux-arm64.zip duration=2m47.493s
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • building        target=deb arch=arm64 file=dist/balena-etcher_1.5.113_arm64.deb
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86/fpm-1.9.3-2.3.1-linux-x86.7z size=4.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86/fpm-1.9.3-2.3.1-linux-x86.7z duration=1m6.266s
  ⨯ cannot execute  cause=exit status 1
```

my sys arch is arm64 , but it download the x86 arch binaries. 
> - fpm-1.9.3-2.3.1-linux-x86

and  my build code are: 
```
git clone --recursive https://github.com/balena-io/etcher.git
cd etcher
make electron-develop
PATH=$(pwd)/node_modules/.bin:$PATH electron-builder --linux deb --arm64
```

### LINKED ISSUE #3653: Incorrect SHA512 checksum in latest.yml
- **Etcher version: 1.7.1** 
- **Operating system and architecture: NA** 
- **Image flashed: NA** 
- **Do you see any meaningful error information in the DevTools?** 

**latest.yml** file contains incorrect SHA512 checksum for the latest **balenaEtcher-Setup-1.7.1.exe** download.

Contains: **byitThHrH8eTAwIGVi9IMxBEtfJe+tO4XOE9eREds6S12GiWuIA9TFNFsQg1yEsoDbNdWKKXd2dF8Ug8394RUQ==**
Download is: **6f28ad4e11eb1fc793030206562f48331044b5f25efad3b85ce13d79111db3a4b5d86896b8803d4c5345b10835c84b280db35d58a297776745f1483cdfde1151**

It doesn't actually look like a SHA512 checksum, it looks like something has been base64 encoded, but I got gibberish when decoding it.

### LINKED ISSUE #3728: Provide builds for Apple Silicon Macs

### LINKED ISSUE #3767: Electron 12 used by etcher is EOL (end of life)
Electron 12 used by etcher is EOL (end of life). Installing it on NixOS results in a warning which is quite annoying. It would be great to update to a newer Electron version.

- **Etcher version:** latest
- **Operating system and architecture:** NixOS
- **Image flashed:** 
- **What do you think should have happened:** 
- **What happened:**
- **Do you see any meaningful error information in the DevTools?**

### LINKED ISSUE #4087: [Request] Please support newer electron.
**Note**: This is a custom-rebuilt version with `electron25`, as electron19 has been dropped in archlinux official repo, I tried to rebuild `etcher` with newer `electron` (namely `electron` 22 to 25). 
All builds succeded but failed to flash any image.

---
update: with 1.18.13 I still cannot flash any image. When I select an image, it pops
image
And I see the logs in console says
```
index.css:1     Failed to load resource: net::ERR_FILE_NOT_FOUND
gui.js:320  _____ _       _
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Interested in joining the Etcher team?
Drop us a line at join+etcher@balena.io

Version = 1.18.13, Type = local
node:events:491 Uncaught Error: spawn /usr/lib/balena-etcher/generated/etcher-util ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gui.js:3 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
（anonymous） @ gui.js:3
gui.js:3 TypeError: requestMetadata is not a function
    at gui.js:278:1759
    at SourceSelector.selectSource (gui.js:278:2719)
    at SourceSelector.openImageSelector (gui.js:278:3117)
（anonymous） @ gui.js:3
```
---

But `etcher` built with `electron19` works fine.

My build script: [github gist](https://gist.github.com/sukanka/ba311ab94dd29dec228c9940bd45904a)

- **Etcher version:** 1.18.11
- **Operating system and architecture:** Archlinux x86_64 
- **Image flashed:** [archlinux-2023.07.01-x86_64.iso](https://mirrors.bfsu.edu.cn/archlinux/iso/2023.07.01/archlinux-2023.07.01-x86_64.iso) (or any other)
- **What do you think should have happened:**  flashed successfully.
- **What happened:** 
Failed to flash (any) image.

After the password is entered, the following error occurs.

image

- **Do you see any meaningful error information in the DevTools?** 

image

text version for copy and paste:
```js
 _____ _       _
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Interested in joining the Etcher team?
Drop us a line at join+etcher@balena.io

Version = 1.18.8, Type = local
gui.js:37 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ gui.js:37
gui.js:37 Elevating command: /usr/lib/electron25/electron /usr/lib/balena-etcher/generated/child-writer.js
gui.js:37 Error: Error invoking remote method 'disable-screensaver': Error: No handler registered for 'disable-screensaver'
    at a.invoke (node:electron/js2c/renderer_init:2:7723)
(anonymous) @ gui.js:37
gui.js:35  0 devices, 0% at 0.00 MB/s (total 0.00 MB/s)  with 0 failed devices
gui.js:37 Message from SafeWebview: %cElectron Security Warning (Insecure Content-Security-Policy) font-weight: bold; This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
gui.js:37 Successfully connected to IPC server: etcher-server-482706, socket root /run/user/1000/
gui.js:37 Image: /home/sukanka/Downloads/chrome/archlinux-2023.07.01-x86_64.iso
gui.js:37 Devices: /dev/sdb
gui.js:37 Auto blockmapping: true
gui.js:37 Decompress first: true
gui.js:37 error Error: Command failed: cd "/home/sukanka"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; bash '/tmp/etcher/balena-etcher-electron-7987c7e8d67d.cmd'"
electron: ../binding.c:595: get_aligned_buffer: Assertion `(napi_create_external_buffer(env, size, ptr, free_aligned, ((void *)0), &buffer)) == napi_ok' failed.
/tmp/etcher/balena-etcher-electron-7987c7e8d67d.cmd: line 91: 482888 Aborted                 (core dumped) '/usr/lib/electron25/electron' '/usr/lib/balena-etcher/generated/child-writer.js'

    at __node_internal_genericNodeError (node:internal/errors:867:15)
    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)
gui.js:37 Terminating IPC server
gui.js:37 Flash results Object
gui.js:37 Error: The elevated process died unexpectedly
    at createError (gui.js:37:221570)
    at Object.createUserError (gui.js:37:221783)
    at gui.js:341:5180
    at async withTmpFile (gui.js:1:720152)
    at async elevateCommand (gui.js:341:4411)
    at async Server.<anonymous> (gui.js:341:8515)
(anonymous) @ gui.js:37
gui.js:37 Error: Error invoking remote method 'enable-screensaver': Error: No handler registered for 'enable-screensaver'
    at a.invoke (node:electron/js2c/renderer_init:2:7723)
(anonymous) @ gui.js:37
```
output from terminal
```shell
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Language changed to: en
packageUpdatable false
ready-to-show: 1.562s

(electron:482616): Gtk-WARNING **: 21:13:02.747: Failed to measure available space: ???????
Error occurred in handler for 'disable-screensaver': Error: No handler registered for 'disable-screensaver'
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:88977)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
(node:482616) Warning: No such label 'ready-to-show' for console.timeEnd()
(Use `electron --trace-warnings ...` to show where the warning was created)
Error occurred in handler for 'enable-screensaver': Error: No handler registered for 'enable-screensaver'
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:88977)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)

(electron:482616): Gtk-WARNING **: 21:13:19.846: Failed to measure available space: ???????

(electron:482616): Gtk-WARNING **: 21:13:20.023: Failed to measure available space: ???????
(node:482616) Warning: No such label 'ready-to-show' for console.timeEnd()

```

- **Supplemental information:** Here is the output by etcher (built with electron19)
Devtools:
```js
Failed to load resource: net::ERR_FILE_NOT_FOUND
gui.js:354  _____ _       _
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Interested in joining the Etcher team?
Drop us a line at join+etcher@balena.io

Version = 1.18.8, Type = local
gui.js:37 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ gui.js:37
gui.js:37 Elevating command: /usr/lib/electron19/electron /usr/lib/balena-etcher/generated/child-writer.js
gui.js:37 Error: Error invoking remote method 'disable-screensaver': No handler registered for 'disable-screensaver'
    at o.invoke (node:electron/js2c/renderer_init:57:526)
(anonymous) @ gui.js:37
gui.js:35  0 devices, 0% at 0.00 MB/s (total 0.00 MB/s)  with 0 failed devices
gui.js:37 Successfully connected to IPC server: etcher-server-496098, socket root /run/user/1000/
gui.js:37 Image: /home/sukanka/Downloads/chrome/archlinux-2023.07.01-x86_64.iso
gui.js:37 Devices: /dev/sdb
gui.js:37 Auto blockmapping: true
gui.js:37 Decompress first: true
gui.js:35 Flashing 1 device, 2% at 16.70 MB/s (total 16.70 MB/s) eta in 50s with 0 failed devices
gui.js:35 Flashing 1 device, 5% at 20.40 MB/s (total 20.40 MB/s) eta in 40s with 0 failed devices
... (flash succeded)
```

terminal:
```bash
➜  ~ balena-etcher-electron
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[496011:0708/212850.125976:ERROR:backend_impl.cc(2020)] Invalid file version or magic
Language changed to: en
packageUpdatable false
ready-to-show: 1.678s

(electron19:496011): Gtk-WARNING **: 21:28:52.139: Failed to measure available space: ???????

(electron19:496011): Gtk-WARNING **: 21:28:56.245: Failed to measure available space: ???????
Error occurred in handler for 'disable-screensaver': No handler registered for 'disable-screensaver'
[496011:0708/212902.878360:ERROR:backend_impl.cc(2020)] Invalid file version or magic
[496011:0708/212902.878474:ERROR:backend_impl.cc(2020)] Invalid file version or magic
(node:496011) Warning: No such label 'ready-to-show' for console.timeEnd()
(Use `electron19 --trace-warnings ...` to show where the warning was created)

(electron19:496011): Gtk-WARNING **: 21:29:10.285: Failed to measure available space: ???????
(node:496011) Warning: No such label 'ready-to-show' for console.timeEnd()

(electron19:496011): Gtk-WARNING **: 21:30:55.384: Failed to measure available space: ???????

(electron19:496011): Gtk-WARNING **: 21:30:55.555: Failed to measure available space: ???????
Error occurred in handler for 'enable-screensaver': No handler registered for 'enable-screensaver'
(node:496011) Warning: No such label 'ready-to-show' for console.timeEnd()

```

### LINKED ISSUE #4103: Release hash sums for AppImage in "latest-linux.yml" gone
- **Etcher version:** not relevant for this issue
- **Operating system and architecture:** not relevant for this issue
- **Image flashed:** not relevant for this issue
- **What do you think should have happened:** the release artifact `latest-linux.yml` should have containted the base64 encoded sha512sum of the `.AppImage` release artifact
- **What happened:** Up until release `1.18.8`, the `latest-linux.yml` release artifact contained the base64 encoded sha512sum of the `.AppImage` release artifact, but from version `1.18.9` on, the hash sum for the `.AppImage` does not seem to be released as artifact anymore. The `latest-linux.yml` now contains the base64 encoded sha512sum of the 64 bit debian package. Unfortunately, also no other `.yml` file contains a hash sum for the `.AppImage` artifact.
- **Do you see any meaningful error information in the DevTools?** not relevant

Up until `1.18.8` - `latest-linux.yml`:
```
version: 1.18.8
files:
  - url: balenaEtcher-1.18.8-x64.AppImage
    sha512: oy0igwNmAjuv3Fb74KySK2scsQYMOWqg1QoQOqe9Qr9r+/HoGBoAIQ0DCUu4cj5KcnWqhC0emoXQvOVC64Kt3A==
    size: 99670674
    blockMapSize: 105126
path: balenaEtcher-1.18.8-x64.AppImage
sha512: oy0igwNmAjuv3Fb74KySK2scsQYMOWqg1QoQOqe9Qr9r+/HoGBoAIQ0DCUu4cj5KcnWqhC0emoXQvOVC64Kt3A==
releaseDate: '2023-04-26T09:42:25.874Z'
stagingPercentage: "100"
```

From `1.18.9` - `latest-linux.yml`:
```
version: 1.18.9
files:
  - url: balena-etcher_1.18.9_amd64.deb
    sha512: rF9LPcOlqgOSD8lc99Gj/BgMZuPRxCa558/6K8sNebqLQiHoBfWy12uGoUnX8AJ0m/+XOmfGssFs9cyaxFdPMg==
    size: 90103074
path: balena-etcher_1.18.9_amd64.deb
sha512: rF9LPcOlqgOSD8lc99Gj/BgMZuPRxCa558/6K8sNebqLQiHoBfWy12uGoUnX8AJ0m/+XOmfGssFs9cyaxFdPMg==
releaseDate: '2023-07-12T08:53:38.340Z'
stagingPercentage: "100"
```

I can haz hash sums for `.AppImage` again? 🥺

Cheers
Thomas

### LINKED ISSUE #4119: v1.18.13 (preview) has no macos build
We just built v1.18.13. It's not a production release (it's a preview).
We're refactoring to unlock electron updates to latest.

Note that this work is not finished yet and that's why this is a preview release for which there's no mac build.

If you like living on the edge, give it a go and tell us if you find regressions :)

### LINKED ISSUE #4125: Automatic Winget manifest submission is broken
- **Etcher version:** Latest versions
- **Operating system and architecture:** Windows 10 & Windows 11 (all supported architectures)
- **Image flashed:** none
- **What do you think should have happened:**  Every new release of Balena Etcher automatically submits manifest to [Winget-pkgs repository](https://github.com/microsoft/winget-pkgs) via corresponding [GitHub action](https://github.com/balena-io/etcher/actions/workflows/winget.yml).
- **What happened:** Something broke since https://github.com/balena-io/etcher/pull/3780. As a result, manifests are submitted by the community manually, and not every single version is submitted.
- **Do you see any meaningful error information in the DevTools?** no

### LINKED ISSUE #4129: Bug, Something went wrong...
Etcher version 1.18.13
Debian 12, kernel 6.1.0-13-amd64
Installed file: balena-etcher_1.18.13_amd64.deb

ctr+shift+i output:

gui.js:3 Successfully connected to IPC server: etcher-server-17434-1698307638907-unprivileged}}, socket root /run/user/1000/
gui.js:3 Object
gui.js:3 Error: Error invoking remote method 'disable-screensaver': Error: No handler registered for 'disable-screensaver'
    at a.invoke (node:electron/js2c/renderer_init:2:7723)
(anonymous) @ gui.js:3
gui.js:1  0 devices, 0% at 0.00 MB/s (total 0.00 MB/s)  with 0 failed devices
gui.js:3 Successfully connected to IPC server: etcher-server-17434-1698307648088-privileged}}, socket root /run/user/1000/
gui.js:3 params Object
gui.js:3 Image: /home/xyz/Downloads/xyz.iso
gui.js:3 Devices: /dev/sdc
gui.js:3 Auto blockmapping: false
gui.js:3 Decompress first: true
gui.js:3 fail event
gui.js:3 Object
gui.js:3 Object
gui.js:3 Flash results Object
gui.js:3 Object
gui.js:3 Terminating IPC server
gui.js:3 Error: The writer process ended unexpectedly
    at createError (gui.js:3:225919)
    at Object.createUserError (gui.js:3:226132)
    at finish (gui.js:307:2613)
    at Server.onFail (gui.js:307:2100)
    at Server.emit (gui.js:3:445008)
    at Server.gotData (gui.js:3:450365)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
(anonymous) @ gui.js:3
gui.js:3 Error: Error invoking remote method 'enable-screensaver': Error: No handler registered for 'enable-screensaver'
    at a.invoke (node:electron/js2c/renderer_init:2:7723)
(anonymous) @ gui.js:3
gui.js:1  0 devices, 0% at 0.00 MB/s (total 0.00 MB/s)  with 0 failed devices

### LINKED ISSUE #4136: `.resinci.json` missing, but still needed for `make electron-build`
- **Etcher version:** v1.18.12 and v1.18.13
- **Operating system and architecture:**  Kubuntu 23.10 x64
- **Image flashed:** N/A
- **Reproduction process:**
```bash
git clone git@github.com:balena-io/etcher.git
cd etcher
make electron-develop
make electron-build
```
- **What do you think should have happened:** deb, rpm and appImage should build
- **What happened:**
```
mkdir dist
mkdir dist/.tmp
./scripts/resin/electron/build.sh \
        -b /home/pieter/code/etcher \
        -r x64 \
        -s linux \
        -v production \
        -n dist/.tmp/npm
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/home/pieter/code/etcher/.resinci.json'
Require stack:
- /home/pieter/code/etcher/scripts/resin/electron/extend-electron-builder-config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/pieter/code/etcher/scripts/resin/electron/extend-electron-builder-config.js:39:32)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pieter/code/etcher/scripts/resin/electron/extend-electron-builder-config.js'
  ]
}

Node.js v18.18.2
make: *** [Makefile:105: electron-build] Error 1
```
- **Do you see any meaningful error information in the DevTools?** N/A

# Extra info
Currently, my workaround is checking out the latest version of `.resinci.json`

```bash
git checkout 292f86d6f5b0e8dd34cb3dd6e008517f9a066cd0 .resinci.json
```

I'm not familiar with this codebase. It seems that the build procedure has been updated at some point, which made `.resinci.json` obsolete. But `make electron-build` still uses the old build method and needs `.resinci.json`.

### LINKED ISSUE #4138: v1.18.13 on Kubuntu 23.10: "Error: requestMetadata is not a function" when opening image
- **Etcher version:** v1.18.13
- **Operating system and architecture:**  Kubuntu 23.10 x64
- **Image flashed:** debian-12.2.0-i386-netinst.iso (https://cdimage.debian.org/debian-cd/current/i386/iso-cd/debian-12.2.0-i386-netinst.iso)
- **Reproduction process:**
1. Build and install Etcher
```bash
git clone git@github.com:balena-io/etcher.git
cd etcher
# Getting .resinci.json, see issue #4136 
git checkout 292f86d6f5b0e8dd34cb3dd6e008517f9a066cd0 .resinci.json
make electron-develop
# Removing gconf dependencies, see issue #4137
sed -i '/gconf/d' electron-builder.yml
sed -i '/gconf/d' docs/USER-DOCUMENTATION.md
sed -i '/gconf/d' scripts/resin/electron/electron-builder.json
make electron-build
sudo apt install ./dist/balena-etcher-electron_1.18.13+e9697359_amd64.deb
```
2. Open Etcher
3. Pick file
- **What do you think should have happened:** I can continue
- **What happened:**
Message box: Error opening source
```
Something went wrong while opening /home/pieter/downloads/debian-12.2.0-i386-netinst.iso.

Error: requestMetadata is not a function
```
Error message

- **Do you see any meaningful error information in the DevTools?** Nothing in the dev console
# Extra info
v1.18.12 works perfectly when using the same workarounds for:
- #4136
- #4137

### PR DESCRIPTION
**Pull request by dfunckt**
Switch to electron-forge which is now officially adopted by the Electron project. Solves a bunch of issues along the way.

Issues related to experimental v1.18.13:

Closes #4138 
Closes #4129
Closes #4119 

Build related issues:

Closes #4136 
Closes #4125 
Closes #4103 
Closes #4087 
Closes #3767 
Closes #3728 
Closes #3653 
Closes #3400 
Closes #3292 
Closes #3269 
Closes #3263 
Closes #2870 
Closes #2826 

(Admittedly, some of the issues are linked opportunistically -- please reopen them if the issue is not actually solved)

### CODE REVIEW

File: .github/actions/publish/action.yml [hunk 1]
```diff
@@ -94,73 +120,42 @@ runs:
...
+          exit 1
         fi
 
-        npm link electron-builder
-
-        for target in ${TARGETS}; do
-            electron-builder ${ELECTRON_BUILDER_OS} ${target} ${ARCHITECTURE_FLAGS} \
-              --c.extraMetadata.analytics.sentry.token='https://739bbcfc0ba4481481138d3fc831136d@o95242.ingest.sentry.io/4504451487301632' \
-              --c.extraMetadata.analytics.amplitude.token='balena-etcher' \
-              --c.extraMetadata.packageType="${target}"
```
Comment (dfunckt) [inline .github/actions/publish/action.yml:131]: Need to figure out a way to inject these metadata.

File: .github/actions/publish/action.yml [hunk 2]
```diff
@@ -94,73 +120,42 @@ runs:
...
+        XCODE_APP_LOADER_TEAM_ID: ${{ fromJSON(inputs.secrets).XCODE_APP_LOADER_TEAM_ID }}
+        # Windows signing
+        WINDOWS_SIGNING: ${{ fromJSON(inputs.secrets).WINDOWS_SIGNING }}
+        WINDOWS_SIGNING_PASSWORD: ${{ fromJSON(inputs.secrets).WINDOWS_SIGNING_PASSWORD }}
         # https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks
         # https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks
         CSC_FOR_PULL_REQUEST: true
 
-    # https://www.electron.build/auto-update.html#staged-rollouts
-    - name: Configure staged rollout(s)
```
Comment (dfunckt) [inline .github/actions/publish/action.yml:147]: I don't think this actually worked for a while now (or the auto-update mechanism in general). I'll remove everything for now and re-introduce auto-updates properly later on -- Electron Forge has a simple way to do that (but no way for staged rollouts AFAIK)

File: package.json [hunk 3]
```diff
@@ -69,62 +95,71 @@
...
     "tslib": "2.4.1",
     "typescript": "4.4.4",
-    "url-loader": "4.1.1",
-    "uuid": "8.3.2",
-    "webpack": "5.75.0",
-    "webpack-cli": "4.10.0",
-    "webpack-dev-server": "4.11.1"
+    "url-loader": "4.1.1"
+  },
+  "hostDependencies": {
```
Comment (dfunckt) [inline package.json:125]: Not sure how good this choice will turn out to be, but I wanted to avoid what we declare as app dependencies for deb to get out of sync with what we install on CI, so this will have to do for now.

File: forge.config.ts [hunk 4]
```diff
@@ -57,6 +58,9 @@ const config: ForgeConfig = {
   },
   rebuildConfig: {},
   makers: [
+    new MakerPortable({
+			...winSigningConfig,
```
Comment (aethernet) [inline forge.config.ts:62]: This produce a portable .exe but with a generic icon, didn't find yet how to properly set the icon :(
Still digging.

**Comment by dfunckt** [comment]
I self-certify!

**Comment by sid-the-sloth** [comment]
Thank you for shasums!

Gotta love this:

```
$ sha256sum -c --ignore-missing SHA256SUMS.Linux.x64.txt 
balenaEtcher-1.19.0-x64.AppImage: OK
```

**Comment by lurch** [comment]
@dfunckt @aethernet  I've not tested this yet, but congratulations on getting this big update over the line :clap:
